# on:
#   push:
#     branches: ["develop","*"]
  
#   pull_request:
#     branches: ["develop"]

#   release:
#     types: [created]

# name: Test dev commits

# jobs:
#   test:
#      name: Test
#      runs-on: ubuntu-latest
     
#      steps:
#      - name: Checkout
#        uses: actions/checkout@v2
       
#      - name: Install project dependencies
#        run: |
#           npm install
       
#      - name: Run tests
#        run: |
#           sudo npm run test
